/**
 * ==============================================
 * IMPORTANT
 * 
 * Please DO NOT edit this file. 
 * 
 * Use declarations-overrides.js to make 
 * custom modifications and declarations overrides.
 * 
 * ==============================================
 */


let popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
let popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))

let chevronLeftIcon = (w=24, h=24) => `<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-left" width="${w}" height="${h}" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M15 6l-6 6l6 6" /></svg>`;

let chevronRightIcon = (w=24, h=24) => `<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-right" width="${w}" height="${h}" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 6l6 6l-6 6" /></svg>`;

let cmClick = new CustomEvent('click', { bubbles: true, cancelable: true });